### ISSUE TITLE
[bug] Room with name api

### ISSUE THREAD

**Issue by ranomier** [m1k1o/neko-rooms#44]
You can create a room with the name 'api',
it not only becomes not visitable, it also becomes undeletable.

My suggestion would be to make the rooms acceable und example.org/r/<room-name>

It would separate, the manager from the rooms and makes it easier to configure reverse proxies.
I'm running authentik (similar to keycloak, a autentication server) and i had to make a special regex so /api is secured.
This rule would be easier if there where a clear separation between rooms and manager.

What do you think?

This project is awesome, BTW :) :+1:

**Comment by m1k1o** [comment]
Also creating rooms with name `css` and  `js` could be problematic, because then administration would not be available.

When using traefik, I [suggest](https://github.com/m1k1o/neko-rooms/blob/6f4a9429a87612f6dbe91f5b45747b65d7ebabb5/docker-compose.http.yml#L45-L47) to protect the whole adminitration, but that creates a problem with lobby, since that would be then [password protected](https://github.com/m1k1o/neko-rooms/issues/8) too.

You can host administration under different domain by exposing port 8080 directly from neko rooms and revere proxy it. So you could have e.g. `admin.example.org` and `rooms.example.org` domains.

But I agree with you, that it would be easier to have rooms under some (as mentioned `r/`) path prefix. Plan for v2 is to separate lobby and admin completly, and to remove traefik dependency.

What we could do in this verision is to restrict room names (`api`, `css` and  `js`), add optional path-prefix config value to neko-room that would be empty by default (to maintain backward compatibiltiy) but would allow to specify own prefix.

**Comment by ranomier** [comment]
Sounds good :) Thank you :)

**Comment by m1k1o** [comment]
With new proxy, `/api` is registered before room handler. Therefore it makes room named `/api` inaccessible. But with set up path prefix this can be prevented.
